## 1D with Numpy

In [1]:
import numpy as np

In [3]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [5]:
print("Rank of t:", t.ndim)
print("Shape of t:", t.shape) 

Rank of t: 1
Shape of t: (7,)


In [7]:
print("t[0] t[1] t[-1] =", t[0], t[1], t[-1])

t[0] t[1] t[-1] = 0.0 1.0 6.0


In [8]:
print("t[2:5] t[4:-1] =", t[2:5], t[4:-1])

t[2:5] t[4:-1] = [2. 3. 4.] [4. 5.]


In [9]:
print("t[:2] t[3:] =", t[:2], t[3:])

t[:2] t[3:] = [0. 1.] [3. 4. 5. 6.]


## 2D with Numpy

In [10]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [11]:
print("Rank of t:", t.ndim)
print("Shape of t:", t.shape)

Rank of t: 2
Shape of t: (4, 3)


## 1D with PyTorch

In [12]:
import torch

In [13]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [14]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [15]:
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D with PyTorch

In [17]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [18]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [19]:
print(t[:, 1])
print(t[:, 1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [20]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Broadcasting

In [21]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [22]:
# Vector + Scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [24]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # [1, 2] -> [[1, 2], [1, 2]]
m2 = torch.FloatTensor([[3], [4]]) # [3], [4] -> [[3, 3], [4, 4]]
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## Matrix Multiplication VS Multiplication

In [26]:
# Matrix Multiplication
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print("Shape of Matrix1:", m1.shape)
print("Shape of Matrix2:", m2.shape)
print(m1.matmul(m2))

Shape of Matrix1: torch.Size([2, 2])
Shape of Matrix2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [27]:
# Multiplication
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]]) # [[1, 1], [2, 2]]
print("Shape of Matrix1:", m1.shape)
print("Shape of Matrix2:", m2.shape)
print(m1 * m2)
print(m1.mul(m2))

Shape of Matrix1: torch.Size([2, 2])
Shape of Matrix2: torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## Mean

In [28]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [30]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [31]:
print(t.mean())

tensor(2.5000)


In [33]:
print(t.mean(dim=0))

tensor([2., 3.])


In [34]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [35]:
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


## Sum

In [36]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [37]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Max & ArgMax

In [38]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [39]:
print(t.max())

tensor(4.)


In [40]:
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [41]:
print("Max:", t.max(dim=0)[0])
print("Argmax:", t.max(dim=0)[1])

Max: tensor([3., 4.])
Argmax: tensor([1, 1])


In [42]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## View

In [44]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [45]:
print(ft.shape)

torch.Size([2, 2, 3])


In [47]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [48]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze

In [49]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [50]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze

In [51]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [52]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [53]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [54]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [55]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting

In [56]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [57]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [58]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [59]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenate

In [60]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [61]:
print(torch.cat([x, y], dim=0)) # 첫번째 차원을 늘리라는 의미

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [62]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking

In [63]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [64]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [65]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [66]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


# Ones like & Zero like

In [67]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [68]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [69]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation

In [70]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [71]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [72]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
