In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
torch.manual_seed(1)

In [3]:
z = torch.rand(3, 5,  requires_grad=True)

hypothesis = F.softmax(z, dim=1)

print(hypothesis)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward>)


In [4]:
y = torch.randint(5, size=(3, )).long()
print(y)
print(y.unsqueeze(1))

y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(dim=1, index=y.unsqueeze(1), value=1)

tensor([0, 2, 1])
tensor([[0],
        [2],
        [1]])


tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [5]:
# Low level
cost1 = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
print(cost1)

tensor(1.4689, grad_fn=<MeanBackward0>)


In [6]:
# F.softmax() + torch.log() = F.log_softmax()
cost2 = (y_one_hot * -F.log_softmax(z, dim=1)).sum(dim=1).mean()
print(cost2)

tensor(1.4689, grad_fn=<MeanBackward0>)


In [7]:
# (y_one_hot * -X).sum(dim=1).mean() = F.nll_loss(X)
cost3 = F.nll_loss(F.log_softmax(z, dim=1), y)
print(cost3)

tensor(1.4689, grad_fn=<NllLossBackward>)


In [8]:
# F.log_softmax() + F.null_loss() = F.cross_entropy()
cost4 = F.cross_entropy(z, y)
print(cost4)

tensor(1.4689, grad_fn=<NllLossBackward>)
